spring.application.name=erp

# JWT Configuration
app.jwt.secret=mySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLongForHS512Algorithm
app.jwt.expiration-ms=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/erp
spring.datasource.username=mezza
spring.datasource.password=ndaghafijo

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (optional but common)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ingriderik95@gmail.com
spring.mail.password=cxgksvtiwzzybazw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Email sender details
app.email.from=ingriderik95@gmail.com
app.email.name=APECK ERP System
